version: "3"

tasks:
  default:
    cmds:
      - task: generate

  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - |
        protoc \
          -I proto \
          -I ../third_party/googleapis \
          proto/common/common.proto \
          --go_out=./gen --go_opt=paths=source_relative \
          --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
      - |
        protoc \
          -I proto \
          -I ../third_party/googleapis \
          proto/notes/notes.proto \
          --go_out=./gen --go_opt=paths=source_relative \
          --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
      - |
        protoc \
          -I proto \
          -I ../third_party/googleapis \
          proto/updater/updater.proto \
          --go_out=./gen --go_opt=paths=source_relative \
          --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
